# Site wide configuration

title: Mobile Delivery Days
subtitle: March 21-22
locale: en_US
description: The conference that brings dev and ops together around Mobile Application Delivery
logo: site-logo.png
search: true
#url: http://mobiledeliverydays.org
url: #http://localhost:4000

# Jekyll configuration
future: true
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "art", "scripts-ci"]


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: false


# Site owner
owner:
  name: Mobile Delivery Days
  avatar: bio-photo.jpg
  email: info@mobiledeliverydays.org
  disqus-shortname:
  twitter: mobdeliverydays
  facebook: #username
  github: mobiledeliverydays/mobiledeliverydays-website
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-72358961-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
